# Generated by Django 4.2 on 2023-12-08 04:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_con'),
    ]

    operations = [
        migrations.AlterField(
            model_name='con',
            name='email',
            field=models.EmailField(max_length=122, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='reg',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
